//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGD01_2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSGD01_2()
        {
            this.MSGD01_21 = new HashSet<MSGD01_2>();
            this.MSGD01_3 = new HashSet<MSGD01_3>();
        }
    
        public long MD0102_ID { get; set; }
        public string MD0102_APLNO { get; set; }
        public string MD0102_TYPE { get; set; }
        public Nullable<long> MD0102_SOURCEID { get; set; }
        public string MD0102_SENDTYPE { get; set; }
        public string MD0102_RECDEPT { get; set; }
        public string MD0102_RECUSER { get; set; }
        public string MD0102_UNDERTAKER { get; set; }
        public string MD0102_UNDERTAKERNAME { get; set; }
        public string MD0102_UNDERTAKERDEPT { get; set; }
        public string MD0102_UNDERTAKERDEPTNAME { get; set; }
        public string MD0102_UNDERTAKERTITLE { get; set; }
        public string MD0102_UNDERTAKERTITLENAME { get; set; }
        public Nullable<bool> MD0102_READTYPE { get; set; }
        public Nullable<bool> MD0102_COMPLETETYPE { get; set; }
        public Nullable<System.DateTime> MD0102_COMPLETEDATE { get; set; }
        public Nullable<System.DateTime> MD0102_UPDDATE { get; set; }
        public string MD0102_UPDUSER { get; set; }
    
        public virtual MSGD01_1 MSGD01_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSGD01_2> MSGD01_21 { get; set; }
        public virtual MSGD01_2 MSGD01_22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSGD01_3> MSGD01_3 { get; set; }
    }
}
