//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGM01
    {
        public string MM01_WEBORGCODE { get; set; }
        public string MM01_YEAR { get; set; }
        public string MM01_APLTYPE { get; set; }
        public string MM01_APLID { get; set; }
        public string MM01_APLNO { get; set; }
        public Nullable<int> MM01_APLDATE { get; set; }
        public Nullable<short> MM01_APLTIME { get; set; }
        public string MM01_URGUID { get; set; }
        public string MM01_NAME { get; set; }
        public string MM01_DEPTCODE { get; set; }
        public string MM01_DEPTNAME { get; set; }
        public string MM01_TITLCODE { get; set; }
        public string MM01_TITLNAME { get; set; }
        public string MM01_CANLFLAG { get; set; }
        public Nullable<System.DateTime> MM01_CLOSEDATE { get; set; }
        public Nullable<System.DateTime> MM01_UPDDATE { get; set; }
        public string MM01_UPDUSER { get; set; }
    }
}
